# Generated by Django 4.0.4 on 2022-06-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_venue_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_server',
            field=models.BooleanField(default=False),
        ),
    ]
