# Generated by Django 4.0.5 on 2022-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_venue_venue_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_num',
            field=models.CharField(blank=True, default='8396585556', editable=False, max_length=10, unique=True),
        ),
    ]
