# Generated by Django 4.0.5 on 2022-06-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venue_venue_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='location',
            field=models.CharField(choices=[('Bar Vegan', 'Bar Vegan'), ('Sparrow', 'Sparrow'), ('Slutty Vegan', 'Slutty Vegan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_num',
            field=models.CharField(blank=True, default='7282123981', editable=False, max_length=10, unique=True),
        ),
    ]
