# Generated by Django 4.0.5 on 2022-06-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_venue_venue_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_num',
        ),
    ]
