# Generated by Django 4.0.5 on 2022-06-26 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
    ]
