# Generated by Django 4.0.5 on 2022-06-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_maincourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourseIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=30)),
                ('note_about_ingredient', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maincourse')),
            ],
        ),
    ]
