# Generated by Django 4.0.4 on 2022-07-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_serverlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('Bar Vegan', 'Bar Vegan'), ('Sparrow', 'Sparrow'), ('Slutty Vegan', 'Slutty Vegan')], max_length=100)),
                ('entree', models.CharField(choices=[('Steak Fries', 'Steak Fries')], max_length=100)),
                ('drink', models.CharField(choices=[('Still Water', 'Still Water')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
