# Generated by Django 4.0.4 on 2022-07-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customerorder_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrinkIngredient',
        ),
    ]
