# Generated by Django 4.0.4 on 2022-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_sidedishingredient_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='drink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
