# Generated by Django 4.0.4 on 2022-07-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customerorder_drink_delete_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='side',
        ),
        migrations.DeleteModel(
            name='SideDish',
        ),
    ]
