# Generated by Django 4.0.4 on 2022-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_customerorder_side_delete_sidedish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='entree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MainCourse',
        ),
    ]
