# Generated by Django 4.0.4 on 2022-07-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customerorder_entree_delete_maincourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('ingredient1', models.CharField(max_length=100)),
                ('ingredient2', models.CharField(max_length=100)),
                ('ingredient3', models.CharField(max_length=100)),
                ('ingredient4', models.CharField(max_length=100)),
                ('ingredient5', models.CharField(max_length=100)),
                ('ingredient6', models.CharField(max_length=100)),
                ('ingredient7', models.CharField(max_length=100)),
                ('ingredient8', models.CharField(max_length=100)),
                ('ingredient9', models.CharField(max_length=100)),
                ('ingredient10', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
        ),
    ]
