# Generated by Django 4.0.4 on 2022-07-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_maincourse_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('main_course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maincourse')),
            ],
        ),
    ]
