# Generated by Django 4.0.4 on 2022-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_branchmenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchMenu',
            new_name='CustomMenu',
        ),
        migrations.RenameField(
            model_name='custommenu',
            old_name='branch_menu_owner',
            new_name='custom_menu_owner',
        ),
    ]
