# Generated by Django 4.0.4 on 2022-07-09 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_rename_branchmenu_custommenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
