# Generated by Django 4.0.4 on 2022-07-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_menu_menu_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincoursevideo',
            name='main_course_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maincourse'),
        ),
    ]
