# Generated by Django 4.0.4 on 2022-07-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_maincoursevideo_main_course_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient6', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient7', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient8', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient9', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient10', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='SideDishVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('side_dish_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sidedish')),
            ],
        ),
    ]
