# Generated by Django 4.0.5 on 2022-07-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_drink_drinkvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='location',
            field=models.CharField(choices=[('Bar Vegan', 'Bar Vegan'), ('Sparrow', 'Sparrow'), ('Slutty Vegan', 'Slutty Vegan'), ('Restaurant', 'Restaurant')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='venue',
            field=models.CharField(choices=[('Bar Vegan', 'Bar Vegan'), ('Sparrow', 'Sparrow'), ('Slutty Vegan', 'Slutty Vegan'), ('Restaurant', 'Restaurant')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serverlocation',
            name='location',
            field=models.CharField(choices=[('Bar Vegan', 'Bar Vegan'), ('Sparrow', 'Sparrow'), ('Slutty Vegan', 'Slutty Vegan'), ('Restaurant', 'Restaurant')], max_length=100),
        ),
        migrations.CreateModel(
            name='CustomSideDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient6', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient7', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient8', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient9', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient10', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custommenu')),
            ],
        ),
        migrations.CreateModel(
            name='CustomEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient6', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient7', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient8', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient9', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient10', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custommenu')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient6', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient7', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient8', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient9', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient10', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custommenu')),
            ],
        ),
    ]
