# Generated by Django 4.0.5 on 2022-07-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_menu_customdrink_custom_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSideDishVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('custom_side_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customsidedish')),
            ],
        ),
        migrations.CreateModel(
            name='CustomEntreeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('custom_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customentree')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDrinkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('custom_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customdrink')),
            ],
        ),
    ]
