# Generated by Django 4.0.5 on 2022-07-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_rename_select_custom_menu_selectcustommenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectcustommenu',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
