# Generated by Django 4.0.5 on 2022-07-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_custommenu_custom_menu_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommenu',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
